import type { GetServerSidePropsContext } from "next";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import Image from "next/image";
import logo from "../../images/logo.png";
import NavBar from "../components/NavBar";
import { useEffect } from "react";
import { unstable_getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]";

const Landing: NextPage = () => {
  const utils = api.useContext();
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const examples = api.example.getAll.useQuery();
  const test = api.example.createOne.useMutation({
    onSuccess() {
      void utils.example.getAll.invalidate();
    },
  });

  return (
    <>
      <Head>
        <title>Kennekt</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href={"/logo.png"} />
      </Head>
      <main className="min-h-screen bg-[radial-gradient(ellipse_at_bottom_right,_var(--tw-gradient-stops))] from-slate-900 via-slate-800 to-zinc-900">
        <NavBar />
      </main>
    </>
  );
};

export default Landing;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions
  );

  if (session) {
    return {
      redirect: {
        destination: "/home",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
